-- create table Taco_Order (
--                             id number (19,0) not null,
--                             delivery_Name varchar(50) not null,
--                             delivery_Street varchar(50) not null,
--                             delivery_City varchar(50) not null,
--                             delivery_State varchar(2) not null,
--                             delivery_Zip varchar(10) not null,
--                             cc_number varchar(16) not null,
--                             cc_expiration varchar(5) not null,
--                             cc_cvv varchar(3) not null,
--                             placed_at timestamp not null
-- );
--
--
-- create table  Taco (
--                        id number (19,0) not null,
--
--                        name varchar(50) not null,
--                        taco_order number(19,0) not null,
--                        taco_order_key number(19,0) not null,
--                        created_at timestamp not null
-- );
--
--
-- create table  Ingredient_Ref (
--                                  ingredient varchar(4) not null,
--                                  taco number(19,0) not null,
--                                  taco_key number(19,0) not null
-- );
--
-- create table Ingredient (
--                             id varchar(4) not null,
--                             name varchar(25) not null,
--                             type varchar(10) not null
-- );
--
-- alter table Taco
--     add foreign key (taco_order) references Taco_Order(id);
--
-- alter table Ingredient_Ref
--     add foreign key (ingredient) references Ingredient(id);
